# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_diagnostics_myo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 853)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tw_myo_arm = QtWidgets.QTabWidget(self.centralwidget)
        self.tw_myo_arm.setObjectName("tw_myo_arm")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lab_connect = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lab_connect.setFont(font)
        self.lab_connect.setObjectName("lab_connect")
        self.horizontalLayout_3.addWidget(self.lab_connect)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lab_battery = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_battery.setFont(font)
        self.lab_battery.setObjectName("lab_battery")
        self.horizontalLayout_3.addWidget(self.lab_battery)
        self.pb_battery = QtWidgets.QProgressBar(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_battery.setFont(font)
        self.pb_battery.setProperty("value", 24)
        self.pb_battery.setObjectName("pb_battery")
        self.horizontalLayout_3.addWidget(self.pb_battery)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lab_mode = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_mode.setFont(font)
        self.lab_mode.setObjectName("lab_mode")
        self.horizontalLayout_4.addWidget(self.lab_mode)
        self.lab_lock = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_lock.setFont(font)
        self.lab_lock.setObjectName("lab_lock")
        self.horizontalLayout_4.addWidget(self.lab_lock)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lab_vibrate = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_vibrate.setFont(font)
        self.lab_vibrate.setObjectName("lab_vibrate")
        self.horizontalLayout_5.addWidget(self.lab_vibrate)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.pb_vib_long = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_vib_long.setFont(font)
        self.pb_vib_long.setObjectName("pb_vib_long")
        self.verticalLayout_2.addWidget(self.pb_vib_long)
        self.lab_vib_long = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_vib_long.setFont(font)
        self.lab_vib_long.setObjectName("lab_vib_long")
        self.verticalLayout_2.addWidget(self.lab_vib_long)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.pb_vib_medium = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_vib_medium.setFont(font)
        self.pb_vib_medium.setObjectName("pb_vib_medium")
        self.verticalLayout_3.addWidget(self.pb_vib_medium)
        self.lab_vib_medium = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_vib_medium.setFont(font)
        self.lab_vib_medium.setObjectName("lab_vib_medium")
        self.verticalLayout_3.addWidget(self.lab_vib_medium)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.pb_vib_short = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_vib_short.setFont(font)
        self.pb_vib_short.setObjectName("pb_vib_short")
        self.verticalLayout_4.addWidget(self.pb_vib_short)
        self.lab_vib_medium_2 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_vib_medium_2.setFont(font)
        self.lab_vib_medium_2.setObjectName("lab_vib_medium_2")
        self.verticalLayout_4.addWidget(self.lab_vib_medium_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.lab_myo_arm_diag = QtWidgets.QLabel(self.tab_2)
        self.lab_myo_arm_diag.setMinimumSize(QtCore.QSize(200, 200))
        self.lab_myo_arm_diag.setStyleSheet("image: url(:/myo/images/bracelet_myo.PNG);")
        self.lab_myo_arm_diag.setText("")
        self.lab_myo_arm_diag.setObjectName("lab_myo_arm_diag")
        self.horizontalLayout_9.addWidget(self.lab_myo_arm_diag)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lab_fist = QtWidgets.QLabel(self.tab_2)
        self.lab_fist.setMinimumSize(QtCore.QSize(120, 120))
        self.lab_fist.setStyleSheet("image: url(:/gesture/images/gesture_fist.png);")
        self.lab_fist.setText("")
        self.lab_fist.setObjectName("lab_fist")
        self.horizontalLayout_8.addWidget(self.lab_fist)
        self.lab_spread = QtWidgets.QLabel(self.tab_2)
        self.lab_spread.setMinimumSize(QtCore.QSize(120, 120))
        self.lab_spread.setStyleSheet("image: url(:/gesture/images/gesture_spread.png);")
        self.lab_spread.setText("")
        self.lab_spread.setObjectName("lab_spread")
        self.horizontalLayout_8.addWidget(self.lab_spread)
        self.lab_wave_in = QtWidgets.QLabel(self.tab_2)
        self.lab_wave_in.setMinimumSize(QtCore.QSize(120, 120))
        self.lab_wave_in.setStyleSheet("image: url(:/gesture/images/gesture_wave_in.png);")
        self.lab_wave_in.setText("")
        self.lab_wave_in.setObjectName("lab_wave_in")
        self.horizontalLayout_8.addWidget(self.lab_wave_in)
        self.lab_wave_out = QtWidgets.QLabel(self.tab_2)
        self.lab_wave_out.setMinimumSize(QtCore.QSize(120, 120))
        self.lab_wave_out.setStyleSheet("image: url(:/gesture/images/gesture_wave_out.png);")
        self.lab_wave_out.setText("")
        self.lab_wave_out.setObjectName("lab_wave_out")
        self.horizontalLayout_8.addWidget(self.lab_wave_out)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lab_bluetooth = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_bluetooth.setFont(font)
        self.lab_bluetooth.setObjectName("lab_bluetooth")
        self.horizontalLayout_6.addWidget(self.lab_bluetooth)
        self.gv_bluetooth = PlotWidget(self.tab_2)
        self.gv_bluetooth.setMinimumSize(QtCore.QSize(0, 100))
        self.gv_bluetooth.setObjectName("gv_bluetooth")
        self.horizontalLayout_6.addWidget(self.gv_bluetooth)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.tw_myo_arm.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gv_emg_5 = PlotWidget(self.tab)
        self.gv_emg_5.setObjectName("gv_emg_5")
        self.gridLayout.addWidget(self.gv_emg_5, 0, 0, 1, 1)
        self.gv_emg_4 = PlotWidget(self.tab)
        self.gv_emg_4.setObjectName("gv_emg_4")
        self.gridLayout.addWidget(self.gv_emg_4, 0, 1, 1, 1)
        self.gv_emg_3 = PlotWidget(self.tab)
        self.gv_emg_3.setObjectName("gv_emg_3")
        self.gridLayout.addWidget(self.gv_emg_3, 0, 2, 1, 1)
        self.gv_emg_6 = PlotWidget(self.tab)
        self.gv_emg_6.setObjectName("gv_emg_6")
        self.gridLayout.addWidget(self.gv_emg_6, 1, 0, 1, 1)
        self.lab_myo_arm_emg = QtWidgets.QLabel(self.tab)
        self.lab_myo_arm_emg.setStyleSheet("image: url(:/myo/images/bracelet_myo.PNG);")
        self.lab_myo_arm_emg.setText("")
        self.lab_myo_arm_emg.setObjectName("lab_myo_arm_emg")
        self.gridLayout.addWidget(self.lab_myo_arm_emg, 1, 1, 1, 1)
        self.gv_emg_2 = PlotWidget(self.tab)
        self.gv_emg_2.setObjectName("gv_emg_2")
        self.gridLayout.addWidget(self.gv_emg_2, 1, 2, 1, 1)
        self.gv_emg_7 = PlotWidget(self.tab)
        self.gv_emg_7.setObjectName("gv_emg_7")
        self.gridLayout.addWidget(self.gv_emg_7, 2, 0, 1, 1)
        self.gv_emg_8 = PlotWidget(self.tab)
        self.gv_emg_8.setObjectName("gv_emg_8")
        self.gridLayout.addWidget(self.gv_emg_8, 2, 1, 1, 1)
        self.gv_emg_1 = PlotWidget(self.tab)
        self.gv_emg_1.setObjectName("gv_emg_1")
        self.gridLayout.addWidget(self.gv_emg_1, 2, 2, 1, 1)
        self.tw_myo_arm.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gv_gyro = PlotWidget(self.tab_3)
        self.gv_gyro.setObjectName("gv_gyro")
        self.verticalLayout.addWidget(self.gv_gyro)
        self.gv_acc = PlotWidget(self.tab_3)
        self.gv_acc.setObjectName("gv_acc")
        self.verticalLayout.addWidget(self.gv_acc)
        self.gv_ori = PlotWidget(self.tab_3)
        self.gv_ori.setObjectName("gv_ori")
        self.verticalLayout.addWidget(self.gv_ori)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lab_x_value = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_x_value.setFont(font)
        self.lab_x_value.setObjectName("lab_x_value")
        self.gridLayout_2.addWidget(self.lab_x_value, 0, 0, 1, 1)
        self.lab_z_value = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_z_value.setFont(font)
        self.lab_z_value.setObjectName("lab_z_value")
        self.gridLayout_2.addWidget(self.lab_z_value, 0, 1, 1, 1)
        self.lab_y_value = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_y_value.setFont(font)
        self.lab_y_value.setObjectName("lab_y_value")
        self.gridLayout_2.addWidget(self.lab_y_value, 1, 0, 1, 1)
        self.lab_w_value = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_w_value.setFont(font)
        self.lab_w_value.setObjectName("lab_w_value")
        self.gridLayout_2.addWidget(self.lab_w_value, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.pb_set_origin = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_set_origin.setFont(font)
        self.pb_set_origin.setObjectName("pb_set_origin")
        self.horizontalLayout_2.addWidget(self.pb_set_origin)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.gv_cube = QtWidgets.QGraphicsView(self.tab_3)
        self.gv_cube.setObjectName("gv_cube")
        self.horizontalLayout_2.addWidget(self.gv_cube)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tw_myo_arm.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tw_myo_arm)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 935, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tw_myo_arm.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_connect.setText(_translate("MainWindow", "DISCONNECTED"))
        self.lab_battery.setText(_translate("MainWindow", "BATTERYLIFE"))
        self.lab_mode.setText(_translate("MainWindow", "MODE"))
        self.lab_lock.setText(_translate("MainWindow", "Locked / Unlocked"))
        self.lab_vibrate.setText(_translate("MainWindow", "VIBRATE"))
        self.pb_vib_long.setText(_translate("MainWindow", "LONG"))
        self.lab_vib_long.setText(_translate("MainWindow", "100 ms"))
        self.pb_vib_medium.setText(_translate("MainWindow", "MEDIUM"))
        self.lab_vib_medium.setText(_translate("MainWindow", "45 ms"))
        self.pb_vib_short.setText(_translate("MainWindow", "SHORT"))
        self.lab_vib_medium_2.setText(_translate("MainWindow", "23 ms"))
        self.lab_bluetooth.setText(_translate("MainWindow", "BLUETOOTH SIGNAL"))
        self.tw_myo_arm.setTabText(self.tw_myo_arm.indexOf(self.tab_2), _translate("MainWindow", "MyoDiagnostics"))
        self.tw_myo_arm.setTabText(self.tw_myo_arm.indexOf(self.tab), _translate("MainWindow", "EMG graphs"))
        self.lab_x_value.setText(_translate("MainWindow", "x : 0.0000000"))
        self.lab_z_value.setText(_translate("MainWindow", "z : 0.0000000"))
        self.lab_y_value.setText(_translate("MainWindow", "y : 0.0000000"))
        self.lab_w_value.setText(_translate("MainWindow", "w : 0.0000000"))
        self.pb_set_origin.setText(_translate("MainWindow", "SET ORIGIN"))
        self.tw_myo_arm.setTabText(self.tw_myo_arm.indexOf(self.tab_3), _translate("MainWindow", "IMU graphs"))

from pyqtgraph import PlotWidget
import qrc_myo_arm_rc
